name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - mkdocs-deploy

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: 55ce25fcd461a0b18d02f2174c9e32262e2106d3
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base